GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjc0LCJuYW1lIjoiYnVkaSIsImVtYWlsIjoic2F5YUBnbWFpbC5jb20iLCJpYXQiOjE3MDI2NjA0MjEsImV4cCI6MTcwMjY2MDQ1MX0.5JapGorbxZfhjV23ONi9mXsdxkNfPPgRBL96NETD50o

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "budi",
    "email": "saya@gmail.com",
    "password": "12345678"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "saya@gmail.com",
    "password": "12345678"
}


###
GET http://localhost:5000/token


### 
DELETE http://localhost:5000/logout

###
GET http://localhost:5000/ulasan

###
POST http://localhost:5000/ulasan
Content-Type: application/json

{
    "ulasan": "Additionally, ensure that your model (UlasanModel.js) and database connection are correctly set up and that the request body for the Komen route contains the required data (e.g., ulasan). If the issue persists, you might want to check the detailed error message in your server logs to get more information on what went wrong."
    
}

###
GET http://localhost:5000/download-cv/id:

###
POST http://localhost:5000/daftarPemandu

###
GET http://localhost:5000/daftarPemandu


###
GET http://localhost:5000/formpayment


###
POST http://localhost:5000/formpayment
Content-Type: application/json

{
    "nama": "faris",
    "tiket": "2",
   "tanggal": "2023-07-17",
    "paket_wisata":"paket 3",
    "pemandu": "sania",
    "email": "saya@gmail.com",
    "No_hp": "08976543213"
}

###
PUT http://localhost:5000/change-password


###



